
name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Write-Host "${{ secrets.MY_SECRET }}".Length
          Write-Host "${{ secrets.MY_SECRET }}".Substring(2,3)
